### ISSUE TITLE
Event Measurement: Add Keyboard button events

### ISSUE THREAD

**Issue by bastianilso** [med-material/r-shiny-js-data-capture#10]
We would like to track keyboard events, e.g. button presses. Ideally we do this everywhere on the page.

**Comment by bilal-62210** [comment]
@bastianilso  I've found this : 
![image](https://user-images.githubusercontent.com/73820951/198585560-1d9b3d1b-f04d-476c-9340-ece5fec02984.png)
https://www.section.io/engineering-education/keyboard-events-in-javascript/
I think it can be a good thing to try, what do you think?

**Comment by bilal-62210** [comment]
Hi @bastianilso, is this ok for you ?
[log2022-11-1 13-26-31.97Event.csv](https://github.com/med-material/r-shiny-js-data-capture/files/9909762/log2022-11-1.13-26-31.97Event.csv)
