### ISSUE TITLE
Event Measurement: Scroll Wheel (scrolling/zooming)

### ISSUE THREAD

**Issue by bastianilso** [med-material/r-shiny-js-data-capture#11]
We would like to track when users perform scrolling or zooming, for example using the scroll wheel. We need to see which ways we can do this.

**Comment by bilal-62210** [comment]
@bastianilso I think we can use this : 
![image](https://user-images.githubusercontent.com/73820951/198585098-e2f405db-926e-4ea8-8152-151224b3827f.png)
https://www.w3schools.com/jsref/event_onwheel.asp
what do you think about this ?

**Comment by bilal-62210** [comment]
@bastianilso This is my result for this event:
[log2022-10-31 13-2-21.105Event.csv](https://github.com/med-material/r-shiny-js-data-capture/files/9900830/log2022-10-31.13-2-21.105Event.csv)
This event for "scrolling" and "zoom" is called "wheel".
What do you think about that?

**Comment by bastianilso** [comment]
Hi @bilal-62210 it would be nice if we could see whether it was wheel up or wheel down (scrolling up or down). We should be able to get that from the wheelevent in javascript. See e.g. https://www.w3schools.com/jsref/obj_wheelevent.asp

**Comment by bilal-62210** [comment]
@bastianilso please take a look:
[log2022-10-31 14-28-57.363Event.csv](https://github.com/med-material/r-shiny-js-data-capture/files/9901446/log2022-10-31.14-28-57.363Event.csv)
Is this ok for you ?

**Comment by bastianilso** [comment]
@bilal-62210  nice. could we use "wheelUp" and "wheelDown" instead? I think they read more clear than Top/Bottom (usually we say "scrolling up", "scrolling down").
