### ISSUE TITLE
Readme: Add descriptions of logged columns and what they mean

### ISSUE THREAD

**Issue by bastianilso** [med-material/r-shiny-js-data-capture#12]
The data capture system can capture a lot of data now. It would be useful if we document what the different columns mean.

Follow the example from Whack-A-Mole:
https://github.com/med-material/Whack_A_Mole_VR#mole-whacking-data-collection

**Comment by bilal-62210** [comment]
@bastianilso it's done

**Comment by bastianilso** [comment]
@bilal-62210 nice. one more request: please mention all the possible "Event" labels, and potentially turn them into links to the MDN API.

**Comment by bilal-62210** [comment]
@bastianilso It's done
