### ISSUE TITLE
Data Capture: Test with Touch Input

### ISSUE THREAD

**Issue by bastianilso** [med-material/r-shiny-js-data-capture#15]
So far we have tested the JS data capture system with mouse input. However, if people use dashboard from a phone/tablet, then this produces touch input.

Have a look at the API reference:
https://developer.mozilla.org/en-US/docs/Web/API/Touch_events#setting_up_the_event_handlers

Todo:
- implement the event listeners
- test that the touch events are captured, for example by using touch simulation in e.g. firefox and from a real touch-device.

**Comment by bastianilso** [comment]
@bilal-62210 I now have access to the R shiny server. Please put a link in here once your [Whack-A-Mole ](https://github.com/med-material/Whack_A_Mole_RShiny) dashboard fork is online and updated with your code changes. I will then clone it onto the server.

**Comment by bilal-62210** [comment]
@bastianilso this is the link of the fork : https://github.com/bilal-62210/r-shiny-js-data-capture.git

**Comment by bastianilso** [comment]
@bilal-62210 that is not a fork of the whack-a-mole project. that is a fork of the r-shiny-js-data-capture project with a extracted zip file of the whack-a-mole project inside it.

You need to use this button here:
![image](https://user-images.githubusercontent.com/3967945/208064655-bd3f12e5-46b4-4a6e-ad77-4ebabf8e4cd5.png)

See also:
https://docs.github.com/en/get-started/quickstart/fork-a-repo#forking-a-repository

**Comment by bilal-62210** [comment]
@bastianilso like this ? https://github.com/bilal-62210/Whack_A_Mole_RShiny.git

**Comment by bastianilso** [comment]
@bilal-62210 yes, exactly that works. OK I will clone this to the server and send a URL in a minute.

**Comment by bastianilso** [comment]
@bilal-62210 OK, your fork is now hosted here:

https://rehab.shiny.create.aau.dk/Whack_A_Mole_RShiny/

in case you have updates to the code, let me know and I can git pull on the webserver side.

**Comment by bastianilso** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/Pointer_events

**Comment by bilal-62210** [comment]
@bastianilso I've update the fork, can you makes the changes on the server please.

**Comment by bastianilso** [comment]
@bilal-62210 updated.

**Comment by bastianilso** [comment]
Collect the attributes of the pointer events:

Please see the attributes available here:
https://developer.mozilla.org/en-US/docs/Web/API/Pointer_events#pointerevent_interface

In particular we want to create columns for these attributes:
`pointerId`
`width`
`height`
`pressure`
`pointerType`
`isPrimary`

**Comment by bilal-62210** [comment]
@bastianilso  can you update the server for me please.

**Comment by bastianilso** [comment]
@bilal-62210 updated

**Comment by bilal-62210** [comment]
@bastianilso can you update the server please

**Comment by bastianilso** [comment]
@bilal-62210 updated.

**Comment by bilal-62210** [comment]
@bastianilso can you update again the server please, i want to test the "pointer.type" on the phone

**Comment by bilal-62210** [comment]
@bastianilso can you update the server for me please.

**Comment by bastianilso** [comment]
server is updated now
