### ISSUE TITLE
Change Duration column names in Event and Meta CSV files

### ISSUE THREAD

**Issue by bastianilso** [med-material/r-shiny-js-data-capture#16]
When we load data from the CSV data into R studio with LoadFromDirectory(), the dataset contains Duration.x and Duration.y because the Event CSV and Meta CSV each contain a column called Duration. To fix this, I suggest we rename the Meta CSV duration column to e.g ."SessionDuration" and the Event duration to e.g. "DurationSinceStart".

**Comment by bilal-62210** [comment]
@bastianilso i understand what is our issue but this is our Meta CSV and Event CSV:
![image](https://user-images.githubusercontent.com/73820951/209244808-95add832-c7f2-4cf5-874a-13b3aeedd7a5.png)
![image](https://user-images.githubusercontent.com/73820951/209244840-9f354bf7-1add-4b04-a31d-1dae87be2741.png)
And as you can see we don't have the same name for the column
