### ISSUE TITLE
Readme: add instruction how to integrate with dashboard

### ISSUE THREAD

**Issue by bastianilso** [med-material/r-shiny-js-data-capture#20]
It would be nice if the readme showed code snippets explaining 1) how to integrate the data capture system into an html file and 2) how to integrate it into an R dashboard.

**Comment by bilal-62210** [comment]
@bastianilso It's ok for the readme

**Comment by bastianilso** [comment]
Instead of screenshotting code, please put the actual code as text using the "add code" tool:

![image](https://user-images.githubusercontent.com/3967945/215776064-723dbc77-9958-4f25-b8c5-833b6b7a8526.png)

```
12234
123123132
```

or put backticks manually:
![image](https://user-images.githubusercontent.com/3967945/215776154-9e8730cf-42c8-45e2-b6ac-8063dcf59440.png)

**Comment by bilal-62210** [comment]
@bastianilso It's done
