### ISSUE TITLE
Meta Data: Create Meta Data file

### ISSUE THREAD

**Issue by bastianilso** [med-material/r-shiny-js-data-capture#9]
The purpose of the Meta Data CSV file is to log  information on a "meta" level about the data thats currently being logged.
The meta data file only contains 1 row.

Some columns
- `SamplingRate`: This columns indicates how often data is logged per second by ContinuousMeasurement.
- `SessionDuration`: How long time has passed since the beginning of the session

In addition, it should follow the standards defined in issue #4  (have SessionID, Timestamp etc.)

**Comment by bastianilso** [comment]
![image](https://user-images.githubusercontent.com/3967945/199241519-c7c6b131-6036-481c-9abc-b39da1e53015.png)

**Comment by bastianilso** [comment]
1. SessionDuration: how many seconds have passed since logging started. (TimestampEnd - TimestampStart)
2. How many rows of data, was collected.

`Rows of data / Session Duration = SampleRate`

**Comment by bilal-62210** [comment]
@bastianilso  it's ok for the meta file as you can see
![image](https://user-images.githubusercontent.com/73820951/202468636-e1df672c-5072-498a-9e28-ddfdf6c7fbad.png)

**Comment by bastianilso** [comment]
Cool, let's close this for now then.
